require:
  - rubocop-factory_bot

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'spec/support/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'lib/tasks/**/*.rake'

Metrics/MethodLength:
  Max: 15

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

Rails/FilePath:
  EnforcedStyle: arguments

# RSpec specific configurations
RSpec:
  Language:
    Expectations:
      - expect
      - expect_any_instance_of
      - is_expected
    Helpers:
      - let
      - let!
      - subject
      - before
      - after
      - around

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VoidExpect:
  Enabled: false

RSpec/Focus:
  Enabled: false

RSpec/VariableDefinition:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/ReceiveCounts:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

# Rails configurations
Rails/DynamicFindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Enabled: true

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/SafeNavigation:
  ConvertTry: true

Rails/TimeZone:
  EnforcedStyle: flexible

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Rails/Validation:
  Enabled: true 